### ISSUE TITLE
There doesn't seem to be an operation to get all documents

### ISSUE THREAD

**Issue by tfrank64** [cloudant/swift-cloudant#105]
Please include the following information in your ticket.

- SwiftCloudant version(s) that are affected by this issue. All
- Swift version(s)  06/06 binaries
- Platform(s) Mac
- A small code sample that demonstrates the issue.

I plan to create an operation to simply get all documents at once, like the following url:
`https:<dbURL>/<dbName>/_all_docs`

It will support the query documents mentioned [here](https://docs.cloudant.com/database.html#get-documents) for _all_docs.

**Comment by ricellis** [comment]
@tfrank64 thanks for opening this and the associated PR #106 but it is a duplicate of #89 / #102. @rhyshort can you take a look and make sure your branch covers what Taylor needs for his app.

**Comment by rhyshort** [comment]
Will do

**Comment by rhyshort** [comment]
I've checked over both, the branch @tfrank64 has in #106 is covered by #102, there were some behaviour differences which I've corrected. There is a difference in parameters types, the operation in #102 is typed directly to strings, because `_all_docs` operates on docIds, rather than a generic JSON type. #102  also brings in a few more parameters such as `conflicts` to match the API spec in CouchDB.

**Comment by tfrank64** [comment]
@rhyshort that sounds good if there is an existing pull request, it didn't exist in my local SDK, but I guess you guys were working on it.
I can close my pull request, but will #102 be merged soon? My app will be dependent on it's functionality.

**Comment by rhyshort** [comment]
I hope so, it depends on the bandwidth of the reviewers however.
